// IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Questions' AND xtype='U')
// CREATE TABLE Questions (
//     Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
//     ProductId UNIQUEIDENTIFIER NOT NULL,
//     UserId UNIQUEIDENTIFIER NOT NULL,
//     Question NVARCHAR(MAX) NOT NULL,
//     CreatedAt DATETIME DEFAULT GETDATE()
// );

// IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QuestionReplies' AND xtype='U')
// CREATE TABLE QuestionReplies (
//     Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
//     QuestionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Questions(Id) ON DELETE CASCADE,
//     ShopId UNIQUEIDENTIFIER NOT NULL,
//     Reply NVARCHAR(MAX) NOT NULL,
//     CreatedAt DATETIME DEFAULT GETDATE()
// );
